### ISSUE TITLE
Include path spam

### ISSUE THREAD

**Issue by TurkeyMan** [dcourtois/premake-qt#1]
Why this line: https://github.com/dcourtois/premake-qt/blob/master/qt.lua#L185 ??
I don't think moc or qrc ever generate header files do they? I don't think this is necessary...?

**Comment by dcourtois** [comment]
uic does. I should check if the includedir is already added before adding it again though, thanks for the report, I'll try to fix this during the day !

**Comment by dcourtois** [comment]
I was just out of bed when I replied, now that I'm awake, I see that the includedir is done only once for each config (I thought it was done for each file, when I replied this morning)

When you say it spams include path, could you elaborate ?
(I will add a test to only add this include path when a .ui file is detected, but I'd like to know what the spam is)

**Comment by TurkeyMan** [comment]
Oh okay. I'm using Qt5, so no uic. Perhaps also only emit this line if there are any headers emitted?

**Comment by TurkeyMan** [comment]
Yeah sorry, 'spam' in this case should read 'appears once where zero times would be preferable' ;)

**Comment by dcourtois** [comment]
Yes, that's what I thought, but I wanted to be sure :)
And yes, I already pushed a commit that only add the include path when there is a .ui file, so now it should not be added in your case :)
