### ISSUE TITLE
Spaces in paths fails

### ISSUE THREAD

**Issue by redorav** [dcourtois/premake-qt#13]
The uic, moc and other qt tools fail if there are spaces in the paths (this is in VS2017). The simplest solution is to just put quotes at the beginning and end of the paths. I don't know whether this impact MacOS or not but it's probably a really quick fix?

**Comment by dcourtois** [comment]
Hi, thanks for reporting this ! I'll have a look at this as soon as can :)

**Comment by redorav** [comment]
Works perfectly on Windows. I updated, ran the build and just works (TM). Thanks a lot!

**Comment by dcourtois** [comment]
You're welcome :)
