### ISSUE TITLE
Breaks with Premake v5.0.0-alpha13

### ISSUE THREAD

**Issue by ianshowell** [dcourtois/premake-qt#14]
I'm working on a Mac with OS X 10.14.3 and I ran into a bug with the `fcfg` local. When I run `premake5` I get this error:

    Error: [string "src/base/fileconfig.lua"]:62: attempt to index a nil value (local 'fcfg')

Line 62 of my premake file runs: `qt.enable()` and when I downgraded to premake v5.0.0-alpha12, everything worked fine, so I'm pretty sure there was a breaking update in alpha 13 that  is related to this.

**Comment by dcourtois** [comment]
Hi, thanks for reporting this ! I don't have the time to check this right now, but I'll try to have a look as soon as I can :)

**Comment by ianshowell** [comment]
I have removed it and it seems to still be occurring, so I'm guessing there are issues in my premake file. Thanks!
