### ISSUE TITLE
Getting error files not found 

### ISSUE THREAD

**Issue by ccptleu** [dcourtois/premake-qt#2]
Hi,

I followed the instructions you've provided to setup premake scripts for qt.  I run the basic usage example you have provided to test.  However, i'm getting an error that it's unable to files and dlls. I've placed the files into a location where premake5 should be able to pick them up.  I'm using premake 5 with visual studio 2013.

This is the type of error i'm getting.

Error: C:/premake/premake.lua:3: module 'premake-qt/qt.lua' not found:
        no field package.preload['premake-qt/qt.lua']
        no file '.\premake-qt/qt\lua.lua'
        no file 'C:\premake\lua\premake-qt/qt\lua.lua'
        no file 'C:\premake\lua\premake-qt/qt\lua\init.lua'
        no file 'C:\premake\premake-qt/qt\lua.lua'
        no file 'C:\premake\premake-qt/qt\lua\init.lua'
        no file '.\premake-qt/qt\lua.dll'
        no file 'C:\premake\premake-qt/qt\lua.dll'
        no file 'C:\premake\loadall.dll'
        no file '.\premake-qt/qt.dll'
        no file 'C:\premake\premake-qt/qt.dll'
        no file 'C:\premake\loadall.dll'

Thanks,

ccptleu

**Comment by dcourtois** [comment]
Hi,

The guide might be a bit outdated, I will check this today, and I'll let you know how to fix this :) (I'm using an embedded version of my script, so I didn't notice that it didn't work anymore, sorry for the inconvenience !)

**Comment by dcourtois** [comment]
Hi again,

Well, it seems to work fine. I think that you cloned the premake repository in a wrong place. Here, I did the following :
1. Download the latest Premake5 binary (http://premake.github.io/download.html) and unzip it.
2. In the same folder where the Premake5 executable is located, I ran `git clone https://github.com/dcourtois/premake-qt.git`

And it works. Here is how the folders should look :
```
YourProject/
      |------ Premake5.exe
      |------ premake-qt/
                    |------ qt.lua
                    |------ ... (the rest of the files of the extension
```

**Comment by ccptleu** [comment]
Hi,

Thanks for your help and prompt response! 

I checked out the premake-qt folder to be in the same location where premake5.exe is located.  But i'm still getting the same errors when i run premake5 --file=premake.lua vs2013 from the premake scripts folder on Windows. 

I'm using the following folder structure which i think should be fine as long as i'm setting the project location directories correctly in the build scripts.   My other premake scripts (not using qt) also reside in the premake scripts folder structure as well.  

```
My Project 
   |--- premake scripts folder
            |---premake5.exe
            |---premake.lua
            |---premake-qt folder
                 |---qt.lua, qtmodules.lua, _preload.lua, _manifest.lua
```

**Comment by dcourtois** [comment]
Hi,
What is the current working directory when you execute premake5.exe (e.g. what folder are you in when running the premake command) ? And are you using a recent version of Premake5 ?
I can't reproduce the problem here. Would you mind creating a zip file of your project (you can remove all the source files, just leave the stuff related to premake without changing the hierarchy) and send it so that I can try to spot the problem ?

**Comment by ccptleu** [comment]
Hi again,
I'm using premake5 Alpha 7 version.  Here's an example of the project structure i'd like to use.  The folder contains a master solution with two project files in it (one not using Qt and another using Qt). When running the premake command i'm in the project's premake folder.  The example contains a batch file which you can run from the command prompt to reproduce this issue.  

[Project.zip](https://github.com/dcourtois/premake-qt/files/318751/Project.zip)

**Comment by dcourtois** [comment]
Hi,

Sorry for the delay, I just noticed that you replied and sent a sample ! I reproduced the problem, and it seems to come from the `require` command syntax.
I don't know why, but in my projects I usually use the syntax that is used in the `Readme.md` file (that's what I did when I first tried to reproduce your problem) and in your project, it doesn't work.

You can fix this by removing the .lua extension when doing the require :

```
require( "premake-qt/qt" )
```

and it should work (at least it did on your project, on my computer :p)

**Comment by ccptleu** [comment]
Thanks a lot for your help! Don't know why i didn't catch that earlier. :) I'll close off this issue now.
