### ISSUE TITLE
"Default" moc options

### ISSUE THREAD

**Issue by Jarod42** [dcourtois/premake-qt#26]
Some tools (ninja, make) have warning/errors when there are several rules for same target.

Where rules are identical, fix is simple, keep only one of it.
But with non-identical rules, generators have to workaround that or going to error state :-/

Currently, the generators try to workaround that by ignoring one configuration (ninja) or have conditional inside the rule.
Both have their drawback especially when switching configuration.

uic, rcc, lupdate (.ts) doesn't even have parameters depending of configuration.

moc have those possible parameters (include and define), but I would say that in general moc_xxx.cpp doesn't depends of configuration. Even if we might have signal/slot only available in Debug.

With premake-qt,

- moc default output directory is $(objdir) (which seems fine).
- but moc_xxx.cpp does depends of configuration with auto-addition of `includesdirs` and `defines` (even with a simple `NDEBUG`).

I think that `defines` should not be added automatically, but passed via `qtmocargs`.

**Comment by dcourtois** [comment]
Hey, sorry for the (very) late answer.
I'm not really sure I understand the issue. Would you mind giving me examples of what's wrong with the current way it's working?

**Comment by Jarod42** [comment]
Test project can be found there:
https://github.com/Jarod42/premake-sample-projects/tree/master/projects-qt/project-moc

Similar code to avoid external links:
```lua
workspace "Project"
  configurations { "Debug", "Release" } -- Multi configuration needed to spot the issue

  objdir("obj") -- premake adds $(configName)/$(AppName)
  targetdir("bin/%{cfg.buildcfg}")

  qt.enable()
  qtprefix "Qt5"

  filter "configurations:Debug"
    targetsuffix "d"
    defines "DEBUG" -- Different defines in DEBUG and Release
    qtsuffix "d"

  filter "configurations:Release"
    optimize "On"
    symbols "Off"
    defines "NDEBUG" -- Different defines in DEBUG and Release

  filter {}

  project "app"
    kind "ConsoleApp"
    targetname("app")
    files {"src/**.cpp", "src.**.h"} -- With at least one file to moc

    includedirs(path.join(Root, "src"))

    qtmodules { "core" }
```

Resulting in 2 rules (taking ninja example output):
```
build obj/moc_Test.cpp: custom_command ../../src/Test.h
  CUSTOM_COMMAND = sh -c "echo Running moc on Test.h;\"C:/Qt/Qt5.12.12/5.12.12/mingw73_64/bin/moc\" \"../../src/Test.h\" -o \"obj/moc_Test.cpp\"  -DDEBUG -DQT_CORE_LIB -I\"../../src\""
  CUSTOM_DESCRIPTION = custom build obj/moc_Test.cpp

# ERROR: Rule ignored, using the one from app_Debug
# build obj/moc_Test.cpp: custom_command ../../src/Test.h
#   CUSTOM_COMMAND = sh -c "echo Running moc on Test.h;\"C:/Qt/Qt5.12.12/5.12.12/mingw73_64/bin/moc\" \"../../src/Test.h\" -o \"obj/moc_Test.cpp\"  -DNDEBUG -DQT_CORE_LIB -I\"../../src\""
#   CUSTOM_DESCRIPTION = custom build obj/moc_Test.cpp
```
so
`moc test.h -o moc_test.cpp -DDebug` versus `moc test.h -o moc_test.cpp -DNDebug`

obj/moc_Test.cpp has 2 rules to build it (Debug and Release), they differ in different `defines`.

As workaround, to avoid the issue, I have to generate (identical) file in different paths...

**Comment by dcourtois** [comment]
Hi again.
I see. But the thing is the moc generated files contain `#includes` directives which need to use the same definitions as the current configuration, otherwise bad things might happen.
This is an issue with generators that don't handle multiple configurations, so I'm gonna close this because I don't want to change the default behavior to accommodate those generators. Especially since there it can very easily being worked around by avoiding outputing generated files into the same folder/same name (which IMO is a bad practice, but that's probably just a matter of taste :))

**Comment by Jarod42** [comment]
@dcourtois:
I mostly talked about `defines` which provoke irrelevant diff but admittedly, we won't want to support that config.

Then default directory should not be the same in multi-config by default.
Notice that `cfg.objdir` is simply `'obj'` whereas `'%{cfg.objdir}'` is `'obj/Release/app'`

> This is an issue with generators that don't handle multiple configurations

With given multi-configuration, no generators can handle that correctly.

> outputting generated files into the same folder/same name (which IMO is a bad practice, but that's probably just a matter of taste :))

It is the default of premake-qt BTW.

It seems not to me a bad practice when file would be identical for all configurations
